# GitHub Pages Configuration
# Enable Jekyll processing
plugins:
  - jekyll-relative-links

# Relative links settings
relative_links:
  enabled: true
  collections: false

# Include assets and build files
include:
  - assets
  - build
  - SEARCH_FEATURES.md

# Exclude unnecessary files
exclude:
  - old
  - "*.bat"
  - "*.ps1"
  - __pycache__
  - "*.pyc"

# Markdown settings
markdown: kramdown
highlighter: rouge

# Site settings for better GitHub Pages compatibility
title: "Documentation Site"
description: "A modern documentation site with advanced search capabilities"
baseurl: ""
url: "https://yourusername.github.io"

# Enable safe mode for GitHub Pages
safe: true
