name: Update Module Configuration

on:
  push:
    branches: [ main ]
    paths:
      - 'assets/data/*.json'
      - 'community_bridge/modules/**'
  workflow_dispatch:

jobs:
  update-config:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Update module configuration
      run: |
        cd tools
        python build-static-config.py

    - name: Check for changes
      id: verify-changed-files
      run: |
        if [ -n "$(git status --porcelain)" ]; then
          echo "changed=true" >> $GITHUB_OUTPUT
        else
          echo "changed=false" >> $GITHUB_OUTPUT
        fi

    - name: Commit updated configuration
      if: steps.verify-changed-files.outputs.changed == 'true'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add assets/js/module-config.js
        git commit -m "Auto-update module configuration [skip ci]"
        git push
