name: Update Documentation Structure

on:
  push:
    branches: [ main, master ]
    paths:
      - 'assets/pages/**'
  pull_request:
    branches: [ main, master ]
    paths:
      - 'assets/pages/**'
  workflow_dispatch:

jobs:
  update-structure:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Run structure generator
      run: |
        cd build
        python generate-structure.py

    - name: Check for changes
      id: verify-changed-files
      run: |
        if [ -n "$(git status --porcelain)" ]; then
          echo "changed=true" >> $GITHUB_OUTPUT
        else
          echo "changed=false" >> $GITHUB_OUTPUT
        fi

    - name: Commit and push changes
      if: steps.verify-changed-files.outputs.changed == 'true'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add assets/pages-structure.json assets/pages-structure-flat.json
        git commit -m "Auto-update pages structure [skip ci]" || exit 0
        git push
